(async function () {
 const root=document.getElementById('commissions-root'); const client=window.supabaseClient||window.supabase;
 const esc=(v)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 if(!client){root.textContent='Connexion indisponible.';return;} const {data:{session}}=await client.auth.getSession(); if(!session){root.innerHTML='<h2>Commissions</h2><p>Connectez-vous pour accéder à cet espace.</p>';return;}
 const {data:pages,error}=await client.from('professional_pages').select('id,name').eq('owner_id',session.user.id); if(error||!pages?.length){root.innerHTML='<h2>Commissions</h2><p>Cet espace est réservé aux propriétaires d’une Page Professionnelle.</p>';return;}
 let page=pages[0]; const api=(() => { const configured=window.API_BASE_URL||window.resolveApiBase?.(); if(configured) return configured.replace(/\/$/,''); const local=['localhost','127.0.0.1','0.0.0.0'].includes(location.hostname); return local ? 'http://'+location.hostname+':5050' : location.origin; })(); const headers={Authorization:`Bearer ${session.access_token}`};
 async function apiJson(url, options={}) { const r=await fetch(url,options); const body=await r.text(); let d={}; try { d=body ? JSON.parse(body) : {}; } catch { const local=['localhost','127.0.0.1','0.0.0.0'].includes(location.hostname); throw Error(local ? `L’API Commissions est indisponible (${api}). Lancez « npm run api » puis rechargez la page.` : "L’API Commissions n’est pas encore disponible sur ce déploiement. Déployez la dernière version Vercel puis réessayez."); } if(!r.ok) throw Error(d.error||'Requête impossible.'); return d; }
 async function load(){const d=await apiJson(`${api}/api/partners/dashboard?page_id=${encodeURIComponent(page.id)}`,{headers}); if(!d.active){root.innerHTML=`<h2>Activez votre partenariat</h2><p>Entrez le code partenaire fourni par XERA1 pour ouvrir votre espace Commissions.</p><input id="partner-code" class="form-input" maxlength="60" placeholder="CODE-PARTENAIRE"><button id="activate-partner" class="btn btn-primary" style="margin-top:12px">Activer le partenariat</button><p id="partner-message"></p>`;document.getElementById('activate-partner').onclick=activate;return;} const m=d.metrics;root.innerHTML=`<h2>Commissions · ${esc(d.partner)}</h2><div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(155px,1fr));gap:12px;margin:18px 0">${[['Total',m.total],['Disponible',m.available],['Versé',m.paid],['Affiliés',m.affiliates],['Dons',m.donations],['Dons éligibles',m.donationGross]].map(([a,b])=>`<div class="settings-section" style="margin:0"><small>${a}</small><strong style="display:block;font-size:1.35rem">${typeof b==='number'?'$'+b.toFixed(2):b}</strong></div>`).join('')}</div><h3>Historique</h3><div style="overflow:auto"><table style="width:100%;border-collapse:collapse"><thead><tr><th>Date</th><th>Don</th><th>Commission</th><th>Statut</th></tr></thead><tbody>${d.commissions.length?d.commissions.map(c=>`<tr><td>${new Date(c.created_at).toLocaleDateString('fr-FR')}</td><td>$${Number(c.amount_gross).toFixed(2)}</td><td>$${Number(c.commission_amount).toFixed(2)}</td><td>${esc(c.status)}</td></tr>`).join(''):'<tr><td colspan="4">Aucune commission pour le moment.</td></tr>'}</tbody></table></div>`;}
 async function activate(){const code=document.getElementById('partner-code').value;const msg=document.getElementById('partner-message');msg.textContent='Activation…';try{await apiJson(`${api}/api/partners/activate`,{method:'POST',headers:{...headers,'Content-Type':'application/json'},body:JSON.stringify({professional_page_id:page.id,code})});load();}catch(e){msg.textContent=e.message||'Activation impossible.';}}
 try{await load();}catch(e){root.textContent=e.message||'Espace indisponible.';}
})();
