import { chromium } from 'playwright';
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage();
page.on('console', msg => console.log('console:', msg.type(), msg.text()));
page.on('pageerror', err => console.log('pageerror:', err.message));
await page.goto('http://127.0.0.1:8000/login.html', { waitUntil: 'domcontentloaded' });
await page.waitForTimeout(2000);
console.log('TITLE:', await page.title());
console.log('FORM:', await page.locator('#auth-form').count());
console.log('GOOGLE_BUTTON:', await page.locator('#google-signin-btn').count());
await browser.close();
